"""
config.py — Project registry for Defects4C.
Maps project name → projects directory version.
"""

PROJECTS_DIR = {
    "ARMmbed___mbedtls": "projects",
    "CESNET___libyang": "projects_v1",
    "CLIUtils___CLI11": "projects_v1",
    "CauldronDevelopmentLLC___cbang": "projects",
    "ClusterLabs___libqb": "projects",
    "DaveGamble___cJSON": "projects",
    "DynamoRIO___dynamorio": "projects_v1",
    "KhronosGroup___SPIRV-Tools": "projects_v1",
    "OpenIDC___cjose": "projects",
    "PCRE2Project___pcre2": "projects",
    "SOCI___soci": "projects_v1",
    "VirusTotal___yara": "projects",
    "Yeraze___ytnef": "projects",
    "apache___arrow": "projects_v1",
    "awslabs___aws-c-common": "projects_v1",
    "bblanchon___ArduinoJson": "projects",
    "curl___curl": "projects",
    "danmar___cppcheck": "projects_v1",
    "dlundquist___sniproxy": "projects",
    "facebook___rocksdb": "projects_v1",
    "fmtlib___fmt": "projects_v1",
    "jqlang___jq": "projects",
    "libevent___libevent": "projects_v1",
    "libgd___libgd": "projects",
    "libuv___libuv": "projects",
    "llvm___llvm-project": "projects_v1",
    "lua___lua": "projects",
    "mdadams___jasper": "projects",
    "mongodb___mongo-c-driver": "projects",
    "nanomsg___nng": "projects_v1",
    "nginx___njs": "projects",
    "php___php-src": "projects",
    "redis___hiredis": "projects",
    "redis___redis": "projects",
    "skypjack___entt": "projects_v1",
    "sqlite___sqlite": "projects",
    "the-tcpdump-group___tcpdump": "projects",
    "uncrustify___uncrustify": "projects_v1",
    "uriparser___uriparser": "projects",
    "webmproject___libvpx": "projects",
    "wez___atomicparsley": "projects",
    "yhirose___cpp-peglib": "projects",
    "zeromq___libzmq": "projects_v1",
    "znc___znc": "projects",
}
